/**:
    ros__parameters:
      csv_file_path: "/aichallenge/workspace/src/aichallenge_submit/dev_packages/aichallenge2024-trajectory-editor/csv/raceline_base_15km.csv"
      publish_on_initialize: true
      wait_seconds: 2.0
